spring.application.name=order-service

spring.mongodb.uri=${MONGO_URI}

# Server Configuration
server.port=${PORT}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

# Product service URL for server-side product data validation
product.service.url=${PRODUCT_SERVICE_URL}

# Import secrets
spring.config.import=optional:classpath:application-secrets.properties